name: deploy book

on:
  push:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Checks that the schemas are valid
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Python info
        run: |
          python --version
          pip list

      - name: Build Book
        run: jupyter-book build .

      - name: Deploy book
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
